{{- if .Values.api.enabled -}}
{{- if .Values.api.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kokkak.fullname" . }}-api
  labels:
    {{- include "kokkak.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kokkak.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- end }}
---
{{- if .Values.worker.enabled -}}
{{- if .Values.worker.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kokkak.fullname" . }}-worker
  labels:
    {{- include "kokkak.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kokkak.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
{{- end }}
