# scripts/dev-tls-setup.ps1
# One-shot setup for local HTTPS (T-08..T-12 stack is already built —
# this script just generates the self-signed cert + wires `.env.dev`):
#
#   1. Generates self-signed cert at certs/localhost.pem + localhost-key.pem
#      (skips if files already exist)
#   2. Patches `.env.dev` with the KOKKAK_TLS__* vars
#      (idempotent — only appends if KOKKAK_TLS__ENABLED is missing)
#   3. Prints next-steps + smoke-test commands
#
# Re-runnable. Safe to invoke from CI / a fresh checkout.
#
# ponytail: one script that does exactly what the user has to do by
# hand per `certs/README.md` + `docs/HTTPS_DEPLOYMENT.md` §1. No
# abstraction layer (no `common.ps1`, no module split) — when we add
# staging/preview TLS later, *then* extract a shared helper.

$ErrorActionPreference = 'Stop'
Set-Location (Join-Path $PSScriptRoot '..')

$certRelPath = 'certs/localhost.pem'
$keyRelPath  = 'certs/localhost-key.pem'
$envFile     = '.env.dev'

# ---- 1. Generate self-signed cert (skips if exists) ----
if ((Test-Path $certRelPath) -and (Test-Path $keyRelPath)) {
    Write-Host ('[dev-tls-setup] cert already exists at ' + $certRelPath + ' — skipping')
} else {
    if (-not (Get-Command openssl -ErrorAction SilentlyContinue)) {
        Write-Error '[dev-tls-setup] openssl not found in PATH. Install OpenSSL or run from Git Bash / WSL.'
    }
    New-Item -ItemType Directory -Force -Path 'certs' | Out-Null

    # Git Bash / MSYS path-mangles `/CN=…` in single-quoted args — escape
    # with `//CN=…` so the Subject lands correctly on Windows shells too.
    & openssl req -x509 -newkey rsa:2048 -nodes `
        -keyout $keyRelPath `
        -out $certRelPath `
        -days 365 `
        -subj '//CN=localhost' `
        -addext 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1'
    if ($LASTEXITCODE -ne 0) { throw 'openssl exited non-zero' }
    Write-Host ('[dev-tls-setup] generated ' + $certRelPath + ' + ' + $keyRelPath)
}

# ---- 2. Patch .env.dev (idempotent) ----
if (-not (Test-Path $envFile)) {
    Write-Error ('[dev-tls-setup] ' + $envFile + ' not found at repo root. Create it from .env.example first.')
}

$existing = Get-Content $envFile -Raw
if ($existing -match 'KOKKAK_TLS__ENABLED') {
    Write-Host ('[dev-tls-setup] TLS vars already present in ' + $envFile + ' — skipping')
} else {
    $tlsBlock = @"

# ---- T-LocalRun: HTTPS for local dev (T-08) ----
# Self-signed cert generated by scripts/dev-tls-setup.ps1.
# Browser / curl will warn about an untrusted CA — that is expected
# for local dev. See docs/HTTPS_DEPLOYMENT.md §1.
KOKKAK_TLS__ENABLED=true
KOKKAK_TLS__CERT_PATH=$certRelPath
KOKKAK_TLS__KEY_PATH=$keyRelPath
# Redirect listener on a second port: keeps :80 free for any local
# webserver. Set to 0 to disable the HTTP→HTTPS redirect.
KOKKAK_TLS__REDIRECT_FROM_PORT=18081
# max-age=0 disables HSTS for dev (we are using a self-signed cert,
# HSTS would lock the browser into trusting it). Set 31536000 for
# production with a real CA-signed cert.
KOKKAK_TLS__HSTS_MAX_AGE_SECS=0
# off for dev — restarts would interrupt testing sessions.
KOKKAK_TLS__AUTO_RELOAD=false
"@
    Add-Content -Path $envFile -Value $tlsBlock
    Write-Host ('[dev-tls-setup] appended TLS vars to ' + $envFile)
}

# ---- 3. Next steps ----
Write-Host ''
Write-Host '[dev-tls-setup] Done. Run:'
Write-Host '  1. pwsh scripts/dev-run.ps1                  (starts API on HTTPS)'
Write-Host '  2. curl.exe -k https://localhost:18080/healthz'
Write-Host '  3. Login:'
Write-Host '       curl.exe -k -X POST https://localhost:18080/api/v1/auth/login \'
Write-Host '         -H ''Content-Type: application/json'' \'
Write-Host '         -d ''{"username":"alice","password":"..."}'''
Write-Host ''
Write-Host '[dev-tls-setup] The browser / curl `-k` flag skips the'
Write-Host '                self-signed cert warning. For production:'
Write-Host '                use Let''s Encrypt (docs/HTTPS_DEPLOYMENT.md §2).'
